Repository echo-webkom/echo-web-cms, pull requests merged in 2021-11, with the labels that each got.

#25 :art: Restructuring of studentgroups
  schemas/StudentGroup.js
Labels: feature :sparkles:, manual work :muscle:

#26 Create LICENSE
  LICENSE
Labels: documentation :memo:

#30 Update Happening.js
  schemas/Happening.js
Labels: documentation :memo:

#36 Revert ":art: small structural change in StudentGroup"
  schemas/StudentGroup.js
Labels: bug :bug:

#39 📝 Fix broken README badge link
  README.md
Labels: bug :bug:
